name: Run PHPUnit Tests

on:
  push:  # This will run the workflow on every push event to any branch
  pull_request:  # This will run the workflow for every pull request event on any branch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, dom, ctype, iconv, json, xml
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit tests/evervault/e2e/