name: Run PHPUnit Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, dom, ctype, iconv, json, xml
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit tests/Evervault/e2e
      env:
        TEST_EV_APP_ID: ${{ secrets.TEST_EV_APP_ID }}
        TEST_EV_API_KEY: ${{ secrets.TEST_EV_API_KEY }}